# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob V
email: thisisrobv@gmail.com
description: >
  I've started this blog with the hope of taking all of the loose
  ideas I have in my head and making them comprehensible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thisisrobv.com" # the base hostname & protocol for your site
twitter_username: thisisrobv
github_username:  robv

# Build settings
markdown: kramdown
